### ISSUE TITLE
Create a project website in GitHub pages

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#11]
The _RaiderPlanner_ project requires a marketing presence (website).  Minimum items to include are:

- An "About" page describing the project
- Information for potential users on how to obtain, install, and use the application
- Information for potential developers on how to contribute to development

There are certainly more things which would make sense for the website.  They should be discussed here before work begins.

Info on GitHub pages: https://help.github.com/articles/what-is-github-pages/

**Comment by LoganRickert** [comment]
Do you have an idea about where you want the files to be?

I think you can have the files either in a separate branch or in a given directory name.

**Comment by rsanchez-wsu** [comment]
I am not sure about that.  I will probably prefer a directory, but I need to look at the GitHub pages documentation to find out the details and ramifications.  I will follow up once I have been able to review that.

**Comment by klemmert** [comment]
Hi, I am interested in this issue! My thought process about how I would want to organize this issue would be:

-main page displaying perhaps a picture or something where users can see what the application/planner looks like for a user as well have icons or a navigation bar that will send people to where they need to go (directions, about, etc)
-a link on the navigation bar or icon where users can download and install no matter where they are on the site
-directions of how to load it on another page
-an about section page that describes what can be done with the planner
-another section page where we can have users learn how to contribute as well as describing what license we're under and certain terms and conditions
-links at the bottom where people can contact, important links, etc
-if we make the planner as an application for a phone, I would make the site compatible for mobile as well (although the site would be responsive already, only some things would probably change for mobile)

I know this issue probably won't be available at the moment since there will be many changes in the planner, but I just wanted to throw out some ideas as well as let you know that I am interested in this.

**Comment by lakerimff** [comment]
I'm interested in this item, would have to figure out to what depth the we describe the use of the application, especially as we're adding and changing functions. Obviously screen shots and simplified directions can help.

**Comment by rsanchez-wsu** [comment]
@LoganRickert After reviewing the GitHub pages documentation, I would like to use the `/docs` folder.  That will also allows the possibility later to generate website content as part of the build.

@klemmert Those ideas all sound very good.  Feel free to begin working on the site even though, as you pointed out, things will likely change rather quickly.  I believe that you should be able to add a `/docs` folder in your fork and do your work there, then submit a pull request when it is ready.  Once I have the `/docs` folder in my repository, I will be able to configure GitHub pages to build the site.

@lakerimff I suspect that there is enough to do here for two.  If you want to coordinate with @klemmert and divide up the tasks, that would be good.  Make sure to check with me once you have decided to make sure that each of you has enough assigned.

**Comment by ribar3** [comment]
I would be very interested in assisting with this. For what it's worth, when I took Web Dev II here in the spring earlier this year, we had a group of 4 create a website for our final project, and that worked out very well. However, if you think that 3 would be too many for this, that's no problem. @rsanchez-wsu

**Comment by rsanchez-wsu** [comment]
@ribar3 I will leave team organization up to the individuals working on the issues.  I suspect that there is enough room to keep lots of folks busy working on aspects of the website.

**Comment by klemmert** [comment]
We have decided the roles that would divy up this issue. I would go ahead and create the main page, a link that will send users to a download page (with instructions on how to download and what is needed to support the download), and I was also style and design the site. The download itself of the project would be temporary as this program is not yet ready, nor executable like we want it to me, but that can be updated later.

@lakerimff will tackle handle the about page (will go over main features of the program, about the make and coders who programmed this planner, and updates on what is new with the planner) and services page (how users can contribute and what licenses and terms we have).

@ribar3 will go and make the logo (related to another issue) for the website/project, and make a tutorial video on how to nagivate the program which will then be embedded in the website. There can be a series of videos if needed in later progress.

We would be using bootstrap, JavaScript, HTML, and CSS for this site.

Would these tasks be fulfilling enough for each of us for our assignment 1? Also, let me know if there are any more features you would like to see in the site (this goes to everyone). Also, would this be submitted as separate pull requests, or just as one whole one?

**Comment by rsanchez-wsu** [comment]
@klemmert @lakerimff @ribar3 those tasks seem sufficient to constitute the Project I assignment.

**Comment by lakerimff** [comment]
@rsanchez-wsu looking at my fork settings, the /doc option is grayed out, is this something that needs to be added under your fork, or the original maybe to allow us to use this as our GitHub Pages option?

**Comment by rsanchez-wsu** [comment]
@lakerimff I will have to push a docs folder so that the setting is enabled.
