### ISSUE TITLE
Re-implement nested if statements

### ISSUE THREAD

**Issue by Smith-Jake** [rsanchez-wsu/RaiderPlanner#41]
Issue:
There are many instances of if statements that are implemented as nested loops. These nested if statements are logically equivalent to an if-else if statement. If implemented in this way, this can save a few lines of code, as well as reduce the startup time and increase the response time of the program. This will also make the code easier to read and follow.

Goal:
Make the code easier to read, reduce the number of lines of code, reduce the startup time, and increase the response time of the program.

Solution:
Convert, where applicable, the nested if statements to if-else if statements, but only if the change is logically equivalent to the original if statements.

Example:
This:

if(condition1) {
    if(condition2) {
        ...code1...
    } else {
        ...code2...
    }
} else {
    ...code3...
}

Becomes this:
if(condition1 && condition2) }
    ...code1...
} else if(condition1 && !condition2) {
    ...code2...
} else if(!condition1) {
    ...code3...
}

**Comment by Matt2233** [comment]
Do you have any set areas of the code that this is an issue? Like, for example, ln 91:134 in DataController.java has two nested if-statements as well as a nested switch statement. If I'm correct, this is the type of problem(s) you're referring to, right?

So, if you can give a list of places this is an issue (10 or so to start) then someone could just grab this and start working on it now for one of their projects.

**Comment by Smith-Jake** [comment]
The two nested if-statements in DataController.java is not exactly what I had in mind, but that could be included in fixing this issue! If it is possible to simply the nested if-statements, while keeping the intended function of that part of code, then go ahead and fix it!

Here are just a few examples in the code that I was referring to in my issue:
VersionControlEntity 116:135
MainController 153:170
MilestoneController 94:106

**Comment by Alienturnedhuman** [comment]
Hi, original PearPlanner team member here.

While the readability point is up for debate, the changes you propose to the code will likely increase the response time of the program (although in most cases probably by sub milliseconds due to CPU speed)

The reason being is that if your example of 



```
if(condition1) {
	if(condition2) {
		...code1...
	} else {
		...code2...
	}
} else {
	...code3...
}
```

Versus

```
if(condition1 && condition2)
{
	...code1...
} else if(condition1 && !condition2) {
	...code2...
} else if(!condition1) {
	...code3...
}
```

In the first example, condition1 is only ever evaluated once, and condition2 only in times where condition1 is true.

In the second example, if condition1 is false, then it will be evaluated three times - now if that's an expensive method that will add three times the overhead needed. If condition2 is false and condition1 is true, then condition1 will be evaluated twice, and condition2 twice as well.

That's the reason for the nested if statements.

It's possible that the JVM may detect optimizations like this (I think GCC usually does) - but at best,  in terms of optimization, this change will be a net zero improvement for application speed, but will probably slow it down.

**Comment by Smith-Jake** [comment]
@Alienturnedhuman Thank you for your insight on the issue. I was unsure myself if the JVM would optimize this type of thing. However, if the fact of the matter is that this will result in either zero improvement or even slowing down the program, then I will close this issue.
